version: "2.4"
volumes:
    cmdbuild-db:
    cmdbuild-tomcat:

services:
    cmdbuild_db:
        image: itmicus/cmdbuild:db-3.0
        container_name: ${POSTGRES_HOST}
        volumes:
            - cmdbuild-db:/var/lib/postgresql
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASS=${POSTGRES_PASS}
        restart: on-failure

    cmdbuild_app:
        image: itmicus/cmdbuild:app-3.1
        container_name: ${CMDBUILD_HOST}
        links:
           - cmdbuild_db
        depends_on:
           - cmdbuild_db
        ports:
            - ${CMDBUILD_PORT}:8080
        volumes:
            - cmdbuild-tomcat:/usr/local/tomcat
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASS=${POSTGRES_PASS}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_DB=${POSTGRES_DB}
            - CMDBUILD_DUMP=${CMDBUILD_DUMP}
            - JAVA_OPTS=-Xmx4000m -Xms4000m
        mem_limit: 4000m
        mem_reservation: 2000m       